services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-evenements
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-evenements:5432/Events-db
      - SPRING_DATASOURCE_USERNAME=dahia
      - SPRING_DATASOURCE_PASSWORD=dahia
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - kafka-network

  postgres-evenements:
    image: postgres:latest
    environment:
      POSTGRES_USER: dahia
      POSTGRES_PASSWORD: dahia
      POSTGRES_DB: Events-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kafka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  pgdata: