version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-evenements
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-evenements:5432/Events-db
      - SPRING_DATASOURCE_USERNAME=dahia
      - SPRING_DATASOURCE_PASSWORD=dahia
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
  postgres-evenements:
    image: postgres:latest
    environment:
      POSTGRES_USER: dahia
      POSTGRES_PASSWORD: dahia
      POSTGRES_DB: Events-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: